[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 119
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
select = [
    # flake8-annotations
    "ANN",
    # flake8-unused-arguments
    "ARG",
    # flake8-bugbear
    "B",
    # flake8-commas
    "COM",
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # eradicate
    "ERA",
    # Pyflakes
    "F",
    # isort
    "I",
    # pep8-naming
    "N",
    # pandas-vet
    "PD",
    # flake8-simplify
    "SIM",
    # pyupgrade
    "UP",
    # Ruff-specific rules
    "RUF100",
    "RUF200",
]
ignore = [
    "ANN101",
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN205",
    "COM819",
    "D100",
    "D400",
    "D401",
    "D415",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
extend-fixable = ["E501", "W505"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

[tool.ruff.isort]
# Split using newline if magic trailing comma is present (which is recommended)
split-on-trailing-comma = true

[tool.ruff.lint.pydocstyle]
convention = "google"
